### ISSUE TITLE
Python script randomly gets stuck after it finishes executing main program

### ISSUE THREAD

**Issue by mosneji** [census-instrumentation/opencensus-python#1126]
**Describe your environment.**
Python version 3.7.11 on Linux, opencensus-ext-azure v1.1.1, AKS v1.22.6.

**Steps to reproduce.**
I have a python scripts which is using opencensus-ext-azure package to export logs to App Insight. It is running on AKS as a job. From time to time, the pod finishes executing the main program but it gets stuck and doesn't exits. I ran the script with "Python -m trace --trace ... " and I saw that it gets stuck in some code coming from the opencensus-ext-azure package.
I cannot reproduce this on demand but I attached  Python execution tracing.

**What is the expected behavior?**
Script exits after it finishes executing the main program.

**What is the actual behavior?**
Script hangs after it finishes executing the main program.

[python_execution_traces.txt](https://github.com/census-instrumentation/opencensus-python/files/8853218/python_execution_traces.txt)

**Comment by lzchen** [comment]
Would  you happen to be using the [metrics](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/examples/metrics/simple.py#L42) exporter?

**Comment by mosneji** [comment]
> Would you happen to be using the [metrics](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/examples/metrics/simple.py#L42) exporter?

I am using AzureLogHandler but maybe that is calling the metrics exporter at some stage?

**Comment by mosneji** [comment]
Ah also, from time to time, I see this message in the logs `warning:opencensus.ext.azure.common.transport:request time out. ingestion may be backed up. retrying.` but I don't necessarily get it whenever the script cannot exit so I am not sure if it is related.

**Comment by mosneji** [comment]
Thank you for looking into this @lzchen. Do you have an estimated release date of the new version? Thanks.

**Comment by lzchen** [comment]
@mosneji 
Will be looking to release by the end of this month.

**Comment by mosneji** [comment]
@lzchen many thanks.

**Comment by nosterlu** [comment]
I have an issue that is maybe related?

From a pull request 2 weeks ago. This started happening just recently. It works in version 1.1.3, but not in 1.1.4

```python
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\temp\Apps\Anaconda64\lib\logging\__init__.py", line 2141, in shutdown
    h.flush()
  File "...\Anaconda64\lib\site-packages\opencensus\ext\azure\log_exporter\__init__.py", line 109, in flush
    if self._queue.is_empty():
AttributeError: 'Queue' object has no attribute 'is_empty'
```

KR
Niklas

**Comment by lzchen** [comment]
@nosterlu 
Just to clarify, in version `1.1.4` you are seeing that error message from time to time but not `1.1.3`?

**Comment by nosterlu** [comment]
My code fails every time with 1.1.4.

In version 1.1.3 this check for `is_empty` does not exist
[log_exporter\__init__.py change for 1.1.4](https://github.com/census-instrumentation/opencensus-python/blob/9ffa48a7dbb7f3fc68bc6cd60ab8d271d08f2c6a/contrib/opencensus-ext-azure/opencensus/ext/azure/log_exporter/__init__.py#L109)

Digging deeper on my end, it seems I have a different version of opencensus common, that is not compatible with 1.1.4? Because `.is_empty` is not a member of my in Queue in `common.schedule.__init__.py`.

I have version 0.8.0 of opencensus, and my [scheulde.__init__.py](https://github.com/census-instrumentation/opencensus-python/blob/0afdcc94021f83a7bdda443530638a2764f2cd30/opencensus/common/schedule/__init__.py#L82) looks like so.

Hmm, when pip installing 1.1.4, is this maybe not forcing opencensus to move to > 0.8.0?

KR
Niklas

**Comment by lzchen** [comment]
Thanks for the investigation. Yes 1.1.4 should have bumped the dependency requirement to `opencensus >= 0.9.0`. I will be doing this as part of next release.

**Comment by mosneji** [comment]
@lzchen I am now using version 1.1.5 but the issue I mentioned is still happening. Any advice? Thanks.

**Comment by lzchen** [comment]
@mosneji 
Could you try upgrading to `opencensus-ext-azure` 1.1.6?

**Comment by mosneji** [comment]
Version 1.1.6 seems to fix the problem. Thanks

**Comment by waldimen** [comment]
Is it fixed ? I have similar problem with the latest version.
